name: Deploy to GitHub Pages

on: 
  push:
    branches: [ main ]

permissions:
  actions: write
  contents: read
  id-token: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Updated to a more recent version for compatibility

      - name: Install dependencies
        run: npm ci  # `npm ci` is faster and more reliable for CI/CD than `npm install`

      - name: Build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./build  # Make sure this matches the output directory of your build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: 'github-pages'
